/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "streamerExtension_autodefs.h"
#include "s3eEdk.h"
#include "streamerExtension.h"
//Declarations of Init and Term functions
extern s3eResult streamerExtensionInit();
extern void streamerExtensionTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult startStreamingAudio_wrap()
{
    IwTrace(STREAMEREXTENSION_VERBOSE, ("calling streamerExtension func on main thread: startStreamingAudio"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)startStreamingAudio, 0);
}

static s3eResult stopStreamingAudio_wrap()
{
    IwTrace(STREAMEREXTENSION_VERBOSE, ("calling streamerExtension func on main thread: stopStreamingAudio"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)stopStreamingAudio, 0);
}

static s3eResult pauseStreamingAudio_wrap()
{
    IwTrace(STREAMEREXTENSION_VERBOSE, ("calling streamerExtension func on main thread: pauseStreamingAudio"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)pauseStreamingAudio, 0);
}

static s3eResult initAudioStream_wrap(const char* ip, int port)
{
    IwTrace(STREAMEREXTENSION_VERBOSE, ("calling streamerExtension func on main thread: initAudioStream"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)initAudioStream, 2, ip, port);
}

#define startStreamingAudio startStreamingAudio_wrap
#define stopStreamingAudio stopStreamingAudio_wrap
#define pauseStreamingAudio pauseStreamingAudio_wrap
#define initAudioStream initAudioStream_wrap

#endif

void streamerExtensionRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[4];
    funcPtrs[0] = (void*)startStreamingAudio;
    funcPtrs[1] = (void*)stopStreamingAudio;
    funcPtrs[2] = (void*)pauseStreamingAudio;
    funcPtrs[3] = (void*)initAudioStream;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[4] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("streamerExtension", funcPtrs, sizeof(funcPtrs), flags, streamerExtensionInit, streamerExtensionTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int streamerExtensionStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&streamerExtensionRegisterExt;
    return 0;
}

int g_streamerExtensionVal = streamerExtensionStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    streamerExtensionRegisterExt();
}
#endif

#endif
