# -*- coding: utf-8 -*-
# Deployment settings for USSCRadio.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Applications/Marmalade.app/Contents/s3e/makefile_builder/mkb.py', '/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/USSCRadio.mkb', '--deploy-only', '--hub-data', '/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/project_USSCRadio/mkb-scons.txt', '--buildenv=SCONS']
mkb = '/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/USSCRadio.mkb'
mkf = ['/Applications/Marmalade.app/Contents/modules/iwutil/iwutil.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libjpeg/libjpeg.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libpng/libpng.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/zlib/zlib.mkf', '/Applications/Marmalade.app/Contents/modules/iw2dscenegraphcore/iw2dscenegraphcore.mkf', '/Applications/Marmalade.app/Contents/modules/iw2dscenegraph/iw2dscenegraph.mkf', '/Applications/Marmalade.app/Contents/modules/iw2d/iw2d.mkf', '/Applications/Marmalade.app/Contents/modules/iwgx/iwgx.mkf', '/Applications/Marmalade.app/Contents/modules/iwgl/iwgl.mkf', '/Applications/Marmalade.app/Contents/modules/iwgeom/iwgeom.mkf', '/Applications/Marmalade.app/Contents/modules/iwresmanager/iwresmanager.mkf', '/Applications/Marmalade.app/Contents/modules/iwgxfont/iwgxfont.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/tiniconv/tiniconv.mkf', '/Applications/Marmalade.app/Contents/modules/iwtween/iwtween.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'USSCRadio'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'USSCRadio'
    long_caption = 'USSCRadio'
    version = [0, 0, 1]
    config = ['/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/data/app.icf']
    data_dir = '/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/data'
    iphone_link_lib = []
    osx_ext_dll = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = []
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = []
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = []
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/debug/USSCRadio.so',
                   'release' : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/release/USSCRadio.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/debug/USSCRadio.s86',
                   'release' : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/release/USSCRadio.s86',
                 },
         'x86' : {
                   'debug'   : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/debug/USSCRadio.s86',
                   'release' : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/release/USSCRadio.s86',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/debug/USSCRadio.so',
                   'release' : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_x86/release/USSCRadio.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_arm/debug/USSCRadio.s3e',
                   'release' : r'/Users/lucasgeiken/Desktop/squareinfinity/USSCRadio/build_usscradio_scons_arm/release/USSCRadio.s3e',
                 },
        }
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
