/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef STREAMEREXTENSION_AUTODEFS_H
#define STREAMEREXTENSION_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_STREAMEREXTENSION_NAME "streamerExtension"
#define S3E_EXT_STREAMEREXTENSION_HASH 0xeb387e45

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("streamerExtension", 4)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !STREAMEREXTENSION_AUTODEFS_H */
